name: Feature Request
description: Suggest an idea for NextAuth.js
labels: [triage, enhancement]

# note: markdown sections will NOT appear as part of the issue as per documentation, rather they provide context to the user
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#markdown

body:
  - type: markdown
    attributes:
      value: |
        **NOTE:** Issues that are potentially security related should be reported to us by following the [Security guidelines](https://next-auth.js.org/security) rather than on GitHub.
        Thank you very much for reaching out to us regarding the awesome feature that you believe should be included in the NextAuth.js library.

        _NOTE: Feature requests are converted to [discussions (Ideas 💡)](https://github.com/nextauthjs/next-auth/discussions/categories/ideas). Make sure your idea hasn't been asked yet, and upvote the existing one before opening a new instead._

        ### Important :exclamation:

        Please proceed by providing the following information:
  - type: textarea
    id: description
    attributes:
      label: Description 📓
      description: Please provide a more in-depth description of the feature proposed.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Make sure you provide plenty of [links]() to external documentation and inline code examples like so:

        ```js
        function myAwesomeNextAuthFeature() {
          return 💚
        }
        ```

        Take time thinking about what you want to say and help us understand your proposal making sure that this description contains:

        - **purpose of the feature**
        - **potential problems**
        - **potential alternatives**

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce ☕️
      description: If you have a CodeSandbox playground or some code snippets to help us visualize your idea better, please provide it here.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can use one of the templates set up on **CodeSandbox** to better illustrate your idea:

        - [`next-auth-example`](https://codesandbox.io/s/next-auth-example-1kktb)

  - type: dropdown
    id: pr
    attributes:
      label: Contributing 🙌🏽
      multiple: false
      options:
        - "Yes, I am willing to help implement this feature in a PR"
        - "No, I am afraid I cannot help regarding this"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        It takes a lot of work 🏋🏻‍♀️ maintaining a library like `next-auth`; any contribution is more than welcome 💚
